version: 0.0
os: linux
files:
  - source: /
    destination: /var/application/l1_automation
permissions:
  - object: /var/application/l1_automation
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 30
      runas: ec2-user
